project_id = "tkgushubkbrjsjaglggu"

[functions.search-pubmed]
verify_jwt = false

[functions.search-clinical-trials]
verify_jwt = false

[functions.search-arxiv]
verify_jwt = false

[functions.search-patents]
verify_jwt = false

[functions.synthesize-results]
verify_jwt = false
